### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by pajowu** [bugbakery/transcribee#171]
We should allow users to change their password. This needs an api call for it as well as ui

**Comment by Nkiriobasi** [comment]
I'll work on this

**Comment by pajowu** [comment]
Great, thank you. There is already a python method to change the password in https://github.com/transcribee/transcribee/blob/126c73d59ccf283f75b24b65d17a652515762ee3/backend/transcribee_backend/auth.py#L128 so the backend part should just be a small wrapper around this

**Comment by pajowu** [comment]
Hey, since I didn't hear back from you for a month, I decided to implement it myself in #269
