### ISSUE TITLE
Bug(?): Alignment is off with repeated text runs

### ISSUE THREAD

**Issue by moeffju** [bugbakery/transcribee#358]
I have an audio file where whisper outputs the following runs sequentially:

* Bitte begrüßt sie mit einem ganz, ganz großen Applaus.
* [Applaus]
* [Applaus]
* [Applaus]
* [Applaus]
* Ja, danke schön.
* Wir haben es eilig, ...

Transcribee appears to have an issue mapping the timestamps of repeated phrases. In the UI of Transcribee, I get the following lines:

Actual:

* 01:24 Bitte begrüßt sie mit einem ganz, ganz großen Applaus. 
* 01:24 [Applaus] Ja, danke schön.
* 01:34 Wir haben es eilig,

Expected:

The first line ends at ~01:27 (the word "Applaus"). Then the audience applauds the speaker, and the "Ja, danke schön" starts at 01:32. From 01:34, the timestamps are correct again. So I would expect the following output:

* 01:24 Bitte begrüßt sie mit einem ganz, ganz großen Applaus. 
* 01:27 [Applaus]
* 01:32 Ja, danke schön.
* 01:34 Wir haben es eilig.

(would also be ok to have "[Applaus]" repeated several times until 01:32).

**Comment by moeffju** [comment]
(Similar alignment errors happen for other mostly non-speech tokens, such as "[Jubel]", as soon as they are repeated.)

**Comment by pajowu** [comment]
This was an issue with our current alignment approach and should be fixed with #397
